### ISSUE TITLE
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

### ISSUE THREAD

**Issue by ghost** [makinacorpus/django-tracking-fields#8]
Hi, 
with version 1.3.4 (and django 3.2.12) , when going to the admin panel and would like to view the data: 

```
ERROR log 2781471 Internal Server Error: /admin/tracking_fields/trackingevent/
Traceback (most recent call last):
  File "[...]lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "[...]lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "[...]lib64/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "[...]lib64/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "[...]lib64/python3.8/site-packages/tracking_fields/admin.py", line 133, in changelist_view
    return super(TrackingEventAdmin, self).changelist_view(
  File "[...]lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "[...]lib64/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/options.py", line 1697, in changelist_view
    cl = self.get_changelist_instance(request)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/options.py", line 736, in get_changelist_instance
    return ChangeList(
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/views/main.py", line 450, in get_queryset
    ) = self.get_filters(request)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/views/main.py", line 137, in get_filters
    spec = list_filter(request, lookup_params, self.model, self.model_admin)
  File "[...]lib64/python3.8/site-packages/django/contrib/admin/filters.py", line 76, in __init__
    lookup_choices = self.lookups(request, model_admin)
  File "[...]lib64/python3.8/site-packages/tracking_fields/admin.py", line 80, in lookups
    ContentType.objects.get_for_id(user['user_content_type'])
  File "[...]lib64/python3.8/site-packages/django/contrib/contenttypes/models.py", line 175, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
  File "[...]lib64/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.
```

**Comment by AL9000** [comment]
I reproduced the bug and fixed it this morning, you can have a look at the linked pull request :)

Thank you for taking the time to log this issue :+1:

**Comment by AL9000** [comment]
Hey @foxmask , we've just released the version containing the changes:
https://github.com/makinacorpus/django-tracking-fields/releases/tag/1.3.6

**Comment by ghost** [comment]
Thanks!
